# Generated by Django 4.1.7 on 2023-03-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_rename_sensor_id_measurement_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='image',
            field=models.ImageField(height_field=60, null=True, upload_to='', width_field=100),
        ),
    ]
