# Generated by Django 4.1.7 on 2023-03-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_measurement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='image',
            field=models.ImageField(height_field=60, max_length=512, null=True, upload_to='', width_field=100),
        ),
    ]
