# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP32",
  "description": "Датчик на кухне за холодильником"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/16/
Content-Type: application/json

{
  "description": "Перенес датчик на подоконник"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 19,
  "temperature": 20.0,
  "image": "C:\\Сергей\\Python\\Курс Нетология\\Django\\dj-homeworks\\3.1-drf-intro\\smart_home\\image\\YEoB7y8OVWyU4gyrxwyfxX2aAY4-1920.jpg"
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/1/
Content-Type: application/json
